#!/bin/bash

# script: get-password(for KeePass)
# Возвращает пароль для доступа с помощью менеджера паролей KeePass
# (через плагин KPScript, https://keepass.info/plugins.html#kpscript).
#
# Использование:
#   get-password URL
#
# Параметры:
# URL                         - URL к ресурсу, для которого нужен пароль
#
# Возврат:
# если удалось определить пароль, то он возвращается через stdoout (иначе
# ничего не возвращается)
#

# Скрипт запроса пароля у менеджера паролей KeePass (через плагин KPScript)
kpPwdScript="/cygdrive/c/KeePass/KPScript.exe"
kpPwdFile="${USERPROFILE}\\work.user.kdbx"

password=""

url=$1

# URL в нижнем регистре
lowerUrl=$(echo "$url" | tr '[:upper:]' '[:lower:]')

# Получение пароля из хранилища
if [[ -x "$kpPwdScript" && -f "$kpPwdFile" ]]; then
  password=$($kpPwdScript -c:GetEntryString -Field=Password -FailIfNotExists -FailIfNoEntry -useraccount "$kpPwdFile" -ref-URL:"$lowerUrl")
  execCode=$?
  if (( ! execCode )); then
    # Убираем хвост из "\nOK: Operation completed successfully."
    password=${password:0:${#password}-40}
  else
    password=""
  fi
fi

# Пробуем подобрать пароль если не удалось определить
if [[ -z "$password" ]]; then
  case $lowerUrl in
    # Для тестовых БД Oracle пробуем тривиальный пароль (имя пользователя
    # в нижнем регистре)
    oracle://*@*t \
    | oracle://*@*t[0-9] \
    | oracle://*@*t[0-9][0-9] \
      )
      password=${lowerUrl%@*}
      password=${password:9}
      ;;
  esac
fi

if [[ -n "$password" ]]; then
  echo $password
fi
exit
