-- script: oms-activate-batch.sql
-- Активирует пакетные задания, реализованные с помощью модуля Scheduler.
--
-- Параметры:
-- patternList                - список масок пакетных заданий ( формат:
--                              список через запятую масок для like имени
--                              пакетного задания с опциональной маской
--                              имени типа пакетного задания вида
--                              [<batchTypePattern>/]<batchPattern>)
--
-- Замечания:
--  - прикладной скрипт, предназначен для вызова из пользовательских скриптов;
--  - в случае, если пакет уже активирован, время очередного запуска будет
--    перерасчитано по расписанию и текущий номер повтора ( если есть) будет
--    сброшен;
--  - для выполнения операции используется скрипт
--    <OmsInternal/exec-batch-operation.sql>
--
-- Примеры:
--
--  - активация батчей ClearOldLog и CheckBatchExecution:
--
-- (code)
--
-- @oms-activate-batch.sql ClearOldLog,CheckBatchExecution
--
-- (end)
--
--  - активация батчей типа RequestProcessing с именами, соответствующими
--    маске %Handler%:
--
-- (code)
--
-- @oms-activate-batch.sql RequestProcessing/%Handler%
--
-- (end)
--

@&OMS_SCRIPT_DIR/OmsInternal/exec-batch-operation.sql ACT "&1" ""
